# Generated by Django 4.1.7 on 2023-03-03 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_feedback_image_feedback_book_feedback_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.book'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
